# Generated by Django 3.2.5 on 2021-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_create_response_paramameter_header_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseparameterheader',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
