# Generated by Django 3.2.5 on 2021-07-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_insert_verbs'),
        ('response', '0002_responseparameterheader_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseParameterHeaderVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verbs', to='response.responseparameterheader')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_headers', to='common.verb')),
            ],
        ),
    ]
