# Generated by Django 3.2.5 on 2021-07-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_insert_verbs'),
        ('response', '0003_create_header_verb_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_created=True)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.verb')),
            ],
        ),
    ]
