# Generated by Django 3.2.5 on 2021-07-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_create_response_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8000)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='response.responseparameterheader')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='response.response')),
            ],
        ),
    ]
