# Generated by Django 3.2.5 on 2021-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_create_response_parameter_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseparameterheader',
            name='key',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
