# Generated by Django 3.2.5 on 2021-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_responseparameterheader_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseparameterheader',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
