# Generated by Django 3.2.5 on 2021-07-31 14:09

from django.db import migrations


def insert_rphs(apps, schema_editor):
    ResponseParameterHeader = apps.get_model(
        'response', 'ResponseParameterHeader')
    headers = [
        ('app_id', 'Appliation ID'),
        ('dev_id', 'Device ID'),
        ('dev_name', 'Device Type'),
        ('time', 'Date and Time'),
        ('dt_flag', 'Flag'),
        ('result', 'Result'),
        ('result_reason', 'Reason'),
        ('spoof_state', 'Spoofing'),
        ('jamming_level', 'CW jamming'),
        ('latitude', 'Latitude'),
        ('longitude', 'Longitude'),
        ('altitude', 'Altitude'),
        ('course', 'Course'),
        ('speed', 'Speed'),
        ('hdop', 'Horizontal Dilution'),
        ('vdop', 'Vertical Dilution'),
        ('gnss_sats', 'GNSS satellites'),
        ('unused', 'Not Used'),
        ('fix_type', 'Fix Type'),
        ('msg_count', 'Message Count'),
        ('data', 'Response Data'),
        ('msg_id', 'Message ID'),
        ('es', 'epoch seconds'),
        ('temp', 'CPU Temperature'),
        ('rssi', 'Signal Strength'),
        ('snr', 'Noise Ratio'),
        ('fdev', 'Frequency Deviation'),
        ('rssi_background', 'Background Noise'),
        ('rssi_sat', 'Signal strength'),
        ('sat_id', 'Satellite ID')
    ]
    for header in headers:
        ResponseParameterHeader.objects.create(
            key=header[0], name=header[1])


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0009_remove_responseparameterheader_description'),
    ]

    operations = [
        migrations.RunPython(insert_rphs),
    ]
