# Generated by Django 3.2.5 on 2021-08-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0013_alter_commandparameter_command'),
        ('response', '0010_insert_rph'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='command.command'),
        ),
    ]
