# Generated by Django 3.2.5 on 2021-08-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0011_response_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='verb',
        ),
    ]
