# Generated by Django 3.2.5 on 2021-07-26 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_insert_verbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.verb')),
            ],
        ),
    ]
