# Generated by Django 3.2.5 on 2021-07-26 13:08

from django.db import migrations


def insert_verb_parameters(apps, schema_editor):
    Verb = apps.get_model('common', 'Verb')
    VerbParameter = apps.get_model('command', 'VerbParameter')
    varb_paramters = [
        ('DT', 1),
        ('GJ', 1),
        ('GN', 1),
        ('GP', 1),
        ('GS', 1),
        ('MM', 1),
        ('MT', 1),
        ('PW', 1),
        ('RT', 1),
        ('SL', 1),
        ('TD', 2)
    ]
    for varb_paramter in varb_paramters:
        verb = Verb.objects.filter(name=varb_paramter[0]).first()
        VerbParameter.objects.create(
            verb=verb, order=varb_paramter[1])


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_create_verb_parameter_table'),
    ]

    operations = [
        migrations.RunPython(insert_verb_parameters),
    ]
