# Generated by Django 3.2.5 on 2021-07-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_insert_verbs'),
        ('command', '0002_insert_verb_parameters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verbparameter',
            unique_together={('verb', 'order')},
        ),
    ]
