# Generated by Django 3.2.5 on 2021-07-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0003_alter_verbparameter_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbParameterLegalString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=8000)),
                ('description', models.TextField()),
                ('verb_parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='command.verbparameter')),
            ],
        ),
    ]
