# Generated by Django 3.2.5 on 2021-07-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0004_create_verb_parameter_legal_string_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verbparameterlegalstring',
            unique_together={('verb_parameter', 'header', 'value')},
        ),
    ]
