# Generated by Django 3.2.5 on 2021-07-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0005_alter_verbparameterlegalstring_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerbParameterLegalString',
            new_name='VerbParameterChoice',
        ),
    ]
