# Generated by Django 3.2.5 on 2021-07-26 16:46

from django.db import migrations


def insert_verb_parameter_choices(apps, schema_editor):
    Verb = apps.get_model('common', 'Verb')
    VerbParameter = apps.get_model('command', 'VerbParameter')
    VerbParameterChoice = apps.get_model(
        'command', 'VerbParameterChoice')
    choices = [

        ('DT', 1, '', '@', 'Repeat most recent DT'),
        ('DT', 1, '', '?', 'Query current DT rate'),
        ('DT', 1, '', 'rate', 'Disable or set rate of DT messages'),

        ('GJ', 1, '', '@', 'Repeat most recent GJ'),
        ('GJ', 1, '', '?', 'Query current GJ rate'),
        ('GJ', 1, '', 'rate', 'Disable or set rate of GJ messages'),

        ('GN', 1, '', '@', 'Repeat most recent GN'),
        ('GN', 1, '', '?', 'Query current GN rate'),
        ('GN', 1, '', 'rate', 'Disable or set rate of GN messages'),

        ('GP', 1, '', '?', 'Display current GPIO1 mode'),
        ('GP', 1, '', '0', 'Analog, pin is internally disconnected and not used'),
        ('GP', 1, '', '1', 'Input, low-to-high transition exits sleep mode'),
        ('GP', 1, '', '2', 'Input, high-to-low transition exits sleep mode'),
        ('GP', 1, '', '3', 'Output, set low'),
        ('GP', 1, '', '4', 'Output, set high'),
        ('GP', 1, '', '5', 'Output, low indicates messages pending for client'),
        ('GP', 1, '', '6', 'Output, high indicates messages pending for client'),
        ('GP', 1, '', '7', 'Output, low while transmitting. Otherwise output is high'),
        ('GP', 1, '', '8', 'Output, high while transmitting. Otherwise output is low'),
        ('GP', 1, '', '9', 'Output, low indicates in sleep mode. Otherwise output is high'),
        ('GP', 1, '', '10', 'Output, high indicates in sleep mode. Otherwise output is low'),

        ('GS', 1, '', '@', 'Repeat most recent GS'),
        ('GS', 1, '', '?', 'Query current GS rate'),
        ('GS', 1, '', 'rate', 'Disable or set rate of GS messages'),

        ('MM', 1, 'C', 'U', 'Return count of unread messages'),
        ('MM', 1, 'C', '*', 'Return count of all received messages'),
        ('MM', 1, 'D', 'msg_id', 'Delete a message by its ID'),
        ('MM', 1, 'D', 'R', 'Delete read messages'),
        ('MM', 1, 'D', '*', 'Delete all received messages'),
        ('MM', 1, 'M', 'msg_id', 'Mark a message as read by its ID'),
        ('MM', 1, 'M', '*', 'Mark all received messages as read'),
        ('MM', 1, 'N', 'D', 'Disable message notifications'),
        ('MM', 1, 'N', 'E', 'Enable message notifications'),
        ('MM', 1, 'N', '?', 'Query message notifications'),
        ('MM', 1, 'R', 'msg_id', 'Read a message by its ID'),
        ('MM', 1, 'R', 'O', 'Read oldest message'),
        ('MM', 1, 'R', 'N', 'Read message newest message'),

        ('MT', 1, 'C', 'U', 'Return count of unsent messages'),
        ('MT', 1, 'D', 'msg_id', 'Delete an unsent message by its ID'),
        ('MT', 1, 'D', 'U', 'Delete all unsent messages'),
        ('MT', 1, 'L', 'msg_id', 'Show an unsent message by its ID'),
        ('MT', 1, 'L', 'U', 'List all unsent messages'),

        ('PW', 1, '', '@', 'Repeat most recent PW'),
        ('PW', 1, '', '?', 'Query current PW rate'),
        ('PW', 1, '', 'rate', 'Disable or set rate of PW messages'),

        ('RT', 1, '', '@', 'Repeat most recent RT'),
        ('RT', 1, '', '?', 'Query current RT rate'),
        ('RT', 1, '', 'rate', 'Disable or set rate of RT messages'),

        ('SL', 1, 'S', 'seconds', 'Sleep for this many seconds'),
        ('TD', 1, 'HD', 'seconds', 'Hold duration of message'),
        ('TD', 2, '', 'free_text', 'Data to transmit'),
    ]
    for choice in choices:
        verb = Verb.objects.filter(name=choice[0]).first()
        verb_parameter = VerbParameter.objects.filter(
            verb=verb, order=choice[1]).first()
        VerbParameterChoice.objects.create(
            verb_parameter=verb_parameter, header=choice[2], value=choice[3], description=choice[4])


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0007_insert_missing_verb_parameters'),
    ]

    operations = [
        migrations.RunPython(insert_verb_parameter_choices),
    ]
