# Generated by Django 3.2.5 on 2021-07-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0008_insert_verb_parameter_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbparameterchoice',
            name='verb_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='command.verbparameter'),
        ),
    ]
