# Generated by Django 3.2.5 on 2021-07-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_insert_verbs'),
        ('command', '0009_alter_verbparameterchoice_verb_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_created=True)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.verb')),
            ],
        ),
        migrations.CreateModel(
            name='CommandParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8000)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='command.command')),
                ('verb_parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='command.verbparameter')),
            ],
        ),
    ]
