# Generated by Django 3.2.5 on 2021-07-27 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0010_create_command_commandparameter_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commandparameter',
            unique_together={('command', 'verb_parameter')},
        ),
    ]
