# Generated by Django 3.2.5 on 2021-07-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_insert_verbs'),
        ('command', '0011_alter_commandparameter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbparameter',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='common.verb'),
        ),
    ]
