# Generated by Django 3.2.5 on 2021-07-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0012_alter_verbparameter_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandparameter',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='command.command'),
        ),
    ]
