# Generated by Django 3.2.6 on 2021-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0013_alter_commandparameter_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
