# Generated by Django 3.2.5 on 2021-07-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_create_verb_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='name',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
