# Generated by Django 3.2.5 on 2021-07-26 12:45

from django.db import migrations


def insert_verbs(apps, schema_editor):
    Verb = apps.get_model('common', 'Verb')
    verbs = [
        ('CS', 'Configuration Settings'),
        ('DT', 'Date/Time Status'),
        ('FV', 'Retrieve Firmware Version'),
        ('GJ', 'GPS Jamming/Spoofing Indication'),
        ('GN', 'Geospatial Information'),
        ('GP', 'GPIO1 Control'),
        ('GS', 'GPS Fix Quality'),
        ('MM', 'Messages Received Management'),
        ('MT', 'Messages to Transmit Management'),
        ('PO', 'Power Off'),
        ('PW', 'Power Status'),
        ('RS', 'Restart Device'),
        ('RT', 'Receive Test'),
        ('SL', 'Sleep Mode'),
        ('TD', 'Transmit Data ')
    ]
    for verb in verbs:
        Verb.objects.create(name=verb[0], description=verb[1])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_make_verb_name_unique'),
    ]

    operations = [
        migrations.RunPython(insert_verbs),
    ]
